#Stage1
FROM node:16.13.2-alpine as builder
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install
RUN npm install
COPY . .
RUN yarn start

#Stage2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf *
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]